services:
  vaultwarden:
    container_name: vaultwarden
    hostname: vaultwarden
    image: vaultwarden/server:latest
    restart: unless-stopped
    volumes:
      #- vaultwarden-data:/data
      - /data/vaultwarden:/data
      - /etc/localtime:/etc/localtime:ro
      - /var/log/vaultwarden:/var/log/vaultwarden
    networks:
      - traefik
    environment:
       # openssl rand -base64 48
       ADMIN_TOKEN: "xxx"
       RUST_BACKTRACE: 1
       LOG_FILE: /var/log/vaultwarden/vaultwarden.log
       WEBSOCKET_ENABLED: "true"
       DOMAIN: https://domain.xyz
       DOMAIN_ORIGIN: https://domain.xyz
    labels:
      # Watchtower
      com.centurylinklabs.watchtower.enable: true
      # Traefik
      traefik.enable: true
      # Web-UI
      traefik.http.routers.vaultwarden.entrypoints: websecure
      traefik.http.routers.vaultwarden.rule: Host(`domain.xyz`)
      traefik.http.routers.vaultwarden.service: vaultwarden-service
      traefik.http.services.vaultwarden-service.loadbalancer.server.port: 80
      traefik.http.routers.vaultwarden.tls: true
      # Websocket
      traefik.http.routers.vaultwarden-ws.entrypoints: websecure
      traefik.http.routers.vaultwarden-ws.rule: Host(`domain.xyz`) && Path(`/notifications/hub`)
      traefik.http.routers.vaultwarden-ws.service: vaultwarden-ws-service
      traefik.http.services.vaultwarden-ws-service.loadbalancer.server.port: 3012
      traefik.http.routers.vaultwarden-ws.tls: true

networks:
  traefik:
    external: true
