# Traefik static config

global:
  checkNewVersion: true
  sendAnonymousUsage: false

entrypoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  traefik:
    address: ":8080"

api:
  dashboard: true

log:
  level: INFO

certificatesResolvers:
  namesilo:
    acme:
      email: email@example.xyz
      storage: "/acme/acme.json"
      dnsChallenge:
        provider: namesilo
        delayBeforeCheck: 900

providers:
  docker:
    watch: true
    network: traefik
    exposedByDefault: false
  file:
    directory: "./dynamic"
    watch: true
